#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config focused_border_color \#730b54
bspc config normal_border_color \#730b54
bspc config window_gap 5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer	true
bspc config automatic_scheme	spiral

bspc config top_padding 0
bspc config left_padding 2
bspc config right_padding 2
bspc config bottom_padding 2

bspc rule -a '*' state=tiled
#bspc rule -a kitty desktop='^1'
bspc rule -a firefox desktop='^2'
bspc rule -a lxappearance desktop='^0'

# Autostart
$HOME/.screenlayout/screen.sh &
picom --backend glx &
polybar &
touchegg &
lxappearance &
sleep 0.1
pkill lxappearance &
picom --experimental-backends --config ~/.config/picom.conf &
feh --bg-fill /home/Aphroth/Pictures/Wallpapers/wings.jpg &
xrandr -s 1360x768 &
